// Mocks generated by Mockito 5.4.6 from annotations
// in search_cms/test/features/dashboard/mocks/dashboard_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:logging/logging.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;
import 'package:powersync_core/src/abort_controller.dart' as _i30;
import 'package:powersync_core/src/connector.dart' as _i28;
import 'package:powersync_core/src/crud.dart' as _i31;
import 'package:powersync_core/src/database/active_instances.dart' as _i27;
import 'package:powersync_core/src/database/powersync_database.dart' as _i25;
import 'package:powersync_core/src/schema.dart' as _i3;
import 'package:powersync_core/src/sync/options.dart' as _i29;
import 'package:powersync_core/src/sync/stream.dart' as _i9;
import 'package:powersync_core/src/sync/sync_status.dart' as _i8;
import 'package:search_cms/core/utils/class_templates/result.dart' as _i2;
import 'package:search_cms/features/dashboard/data/data_sources/abstract_dashboard_api.dart'
    as _i11;
import 'package:search_cms/features/dashboard/data/data_sources/abstract_get_all_sites_api.dart'
    as _i17;
import 'package:search_cms/features/dashboard/data/models/area_model.dart'
    as _i13;
import 'package:search_cms/features/dashboard/data/models/level_model.dart'
    as _i16;
import 'package:search_cms/features/dashboard/data/models/site_area_model.dart'
    as _i14;
import 'package:search_cms/features/dashboard/data/models/site_model.dart'
    as _i12;
import 'package:search_cms/features/dashboard/data/models/unit_model.dart'
    as _i15;
import 'package:search_cms/features/dashboard/domain/entities/area_entity.dart'
    as _i20;
import 'package:search_cms/features/dashboard/domain/entities/level_entity.dart'
    as _i23;
import 'package:search_cms/features/dashboard/domain/entities/site_area_entity.dart'
    as _i21;
import 'package:search_cms/features/dashboard/domain/entities/site_entity.dart'
    as _i19;
import 'package:search_cms/features/dashboard/domain/entities/unit_entity.dart'
    as _i22;
import 'package:search_cms/features/dashboard/domain/repositories/abstract_dashboard_repository.dart'
    as _i18;
import 'package:search_cms/features/dashboard/domain/repositories/abstract_get_all_sites_repository.dart'
    as _i24;
import 'package:sqlite3/common.dart' as _i7;
import 'package:sqlite_async/sqlite_async.dart' as _i4;
import 'package:supabase/supabase.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0 extends _i1.SmartFake implements _i2.Result {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSchema_1 extends _i1.SmartFake implements _i3.Schema {
  _FakeSchema_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSqliteDatabase_2 extends _i1.SmartFake
    implements _i4.SqliteDatabase {
  _FakeSqliteDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogger_3 extends _i1.SmartFake implements _i5.Logger {
  _FakeLogger_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_4 extends _i1.SmartFake implements Duration {
  _FakeDuration_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_5<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIsolateConnectionFactory_6<Database extends _i7.CommonDatabase>
    extends _i1.SmartFake
    implements _i4.IsolateConnectionFactory<Database> {
  _FakeIsolateConnectionFactory_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadQueueStats_7 extends _i1.SmartFake
    implements _i8.UploadQueueStats {
  _FakeUploadQueueStats_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncStream_8 extends _i1.SmartFake implements _i9.SyncStream {
  _FakeSyncStream_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_9 extends _i1.SmartFake
    implements _i10.FunctionsClient {
  _FakeFunctionsClient_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_10 extends _i1.SmartFake
    implements _i10.SupabaseStorageClient {
  _FakeSupabaseStorageClient_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_11 extends _i1.SmartFake
    implements _i10.RealtimeClient {
  _FakeRealtimeClient_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_12 extends _i1.SmartFake
    implements _i10.PostgrestClient {
  _FakePostgrestClient_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_13 extends _i1.SmartFake implements _i10.GoTrueClient {
  _FakeGoTrueClient_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_14 extends _i1.SmartFake
    implements _i10.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_15 extends _i1.SmartFake
    implements _i10.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_16<T1> extends _i1.SmartFake
    implements _i10.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_17 extends _i1.SmartFake
    implements _i10.RealtimeChannel {
  _FakeRealtimeChannel_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AbstractDashboardApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractDashboardApi extends _i1.Mock
    implements _i11.AbstractDashboardApi {
  MockAbstractDashboardApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i12.SiteModel>> getAllSites() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSites, []),
            returnValue: _i6.Future<List<_i12.SiteModel>>.value(
              <_i12.SiteModel>[],
            ),
          )
          as _i6.Future<List<_i12.SiteModel>>);

  @override
  _i6.Future<List<_i13.AreaModel>> getAllAreas() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAreas, []),
            returnValue: _i6.Future<List<_i13.AreaModel>>.value(
              <_i13.AreaModel>[],
            ),
          )
          as _i6.Future<List<_i13.AreaModel>>);

  @override
  _i6.Future<List<_i14.SiteAreaModel>> getAllSiteAreas() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSiteAreas, []),
            returnValue: _i6.Future<List<_i14.SiteAreaModel>>.value(
              <_i14.SiteAreaModel>[],
            ),
          )
          as _i6.Future<List<_i14.SiteAreaModel>>);

  @override
  _i6.Future<List<_i15.UnitModel>> getAllUnits() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUnits, []),
            returnValue: _i6.Future<List<_i15.UnitModel>>.value(
              <_i15.UnitModel>[],
            ),
          )
          as _i6.Future<List<_i15.UnitModel>>);

  @override
  _i6.Future<List<_i16.LevelModel>> getAllLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLevels, []),
            returnValue: _i6.Future<List<_i16.LevelModel>>.value(
              <_i16.LevelModel>[],
            ),
          )
          as _i6.Future<List<_i16.LevelModel>>);

  @override
  _i6.Future<void> createSite({required String? borden, String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#createSite, [], {#borden: borden, #name: name}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createArea({required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#createArea, [], {#name: name}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createSiteArea({
    required String? siteId,
    required String? areaId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSiteArea, [], {
              #siteId: siteId,
              #areaId: areaId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createUnit({
    required String? siteId,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUnit, [], {#siteId: siteId, #name: name}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createLevel({
    required String? unitId,
    required String? name,
    required int? upLimit,
    required int? lowLimit,
    String? parentId,
    String? levelChar,
    int? levelInt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLevel, [], {
              #unitId: unitId,
              #name: name,
              #upLimit: upLimit,
              #lowLimit: lowLimit,
              #parentId: parentId,
              #levelChar: levelChar,
              #levelInt: levelInt,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AbstractGetAllSitesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractGetAllSitesApi extends _i1.Mock
    implements _i17.AbstractGetAllSitesApi {
  MockAbstractGetAllSitesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i12.SiteModel>> getAllSites() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSites, []),
            returnValue: _i6.Future<List<_i12.SiteModel>>.value(
              <_i12.SiteModel>[],
            ),
          )
          as _i6.Future<List<_i12.SiteModel>>);
}

/// A class which mocks [AbstractDashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractDashboardRepository extends _i1.Mock
    implements _i18.AbstractDashboardRepository {
  MockAbstractDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i19.SiteEntity>> getAllSites() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSites, []),
            returnValue: _i6.Future<List<_i19.SiteEntity>>.value(
              <_i19.SiteEntity>[],
            ),
          )
          as _i6.Future<List<_i19.SiteEntity>>);

  @override
  _i6.Future<List<_i20.AreaEntity>> getAllAreas() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAreas, []),
            returnValue: _i6.Future<List<_i20.AreaEntity>>.value(
              <_i20.AreaEntity>[],
            ),
          )
          as _i6.Future<List<_i20.AreaEntity>>);

  @override
  _i6.Future<List<_i21.SiteAreaEntity>> getAllSiteAreas() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSiteAreas, []),
            returnValue: _i6.Future<List<_i21.SiteAreaEntity>>.value(
              <_i21.SiteAreaEntity>[],
            ),
          )
          as _i6.Future<List<_i21.SiteAreaEntity>>);

  @override
  _i6.Future<List<_i22.UnitEntity>> getAllUnits() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUnits, []),
            returnValue: _i6.Future<List<_i22.UnitEntity>>.value(
              <_i22.UnitEntity>[],
            ),
          )
          as _i6.Future<List<_i22.UnitEntity>>);

  @override
  _i6.Future<List<_i23.LevelEntity>> getAllLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLevels, []),
            returnValue: _i6.Future<List<_i23.LevelEntity>>.value(
              <_i23.LevelEntity>[],
            ),
          )
          as _i6.Future<List<_i23.LevelEntity>>);

  @override
  _i6.Future<void> createSite({required String? borden, String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#createSite, [], {#borden: borden, #name: name}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createArea({required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#createArea, [], {#name: name}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createSiteArea({
    required String? siteId,
    required String? areaId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSiteArea, [], {
              #siteId: siteId,
              #areaId: areaId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createUnit({
    required String? siteId,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUnit, [], {#siteId: siteId, #name: name}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createLevel({
    required String? unitId,
    required String? name,
    required int? upLimit,
    required int? lowLimit,
    String? parentId,
    String? levelChar,
    int? levelInt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLevel, [], {
              #unitId: unitId,
              #name: name,
              #upLimit: upLimit,
              #lowLimit: lowLimit,
              #parentId: parentId,
              #levelChar: levelChar,
              #levelInt: levelInt,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AbstractGetAllSitesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractGetAllSitesRepository extends _i1.Mock
    implements _i24.AbstractGetAllSitesRepository {
  MockAbstractGetAllSitesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Result> getAllSites() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSites, []),
            returnValue: _i6.Future<_i2.Result>.value(
              _FakeResult_0(this, Invocation.method(#getAllSites, [])),
            ),
          )
          as _i6.Future<_i2.Result>);
}

/// A class which mocks [PowerSyncDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPowerSyncDatabase extends _i1.Mock implements _i25.PowerSyncDatabase {
  MockPowerSyncDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get closed =>
      (super.noSuchMethod(Invocation.getter(#closed), returnValue: false)
          as bool);

  @override
  _i6.Stream<_i4.UpdateNotification> get updates =>
      (super.noSuchMethod(
            Invocation.getter(#updates),
            returnValue: _i6.Stream<_i4.UpdateNotification>.empty(),
          )
          as _i6.Stream<_i4.UpdateNotification>);

  @override
  _i3.Schema get schema =>
      (super.noSuchMethod(
            Invocation.getter(#schema),
            returnValue: _FakeSchema_1(this, Invocation.getter(#schema)),
          )
          as _i3.Schema);

  @override
  _i4.SqliteDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeSqliteDatabase_2(
              this,
              Invocation.getter(#database),
            ),
          )
          as _i4.SqliteDatabase);

  @override
  _i5.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_3(this, Invocation.getter(#logger)),
          )
          as _i5.Logger);

  @override
  _i8.SyncStatus get currentStatus =>
      (super.noSuchMethod(
            Invocation.getter(#currentStatus),
            returnValue: _i26.dummyValue<_i8.SyncStatus>(
              this,
              Invocation.getter(#currentStatus),
            ),
          )
          as _i8.SyncStatus);

  @override
  _i6.Stream<_i8.SyncStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i6.Stream<_i8.SyncStatus>.empty(),
          )
          as _i6.Stream<_i8.SyncStatus>);

  @override
  _i27.ActiveDatabaseGroup get group =>
      (super.noSuchMethod(
            Invocation.getter(#group),
            returnValue: _i26.dummyValue<_i27.ActiveDatabaseGroup>(
              this,
              Invocation.getter(#group),
            ),
          )
          as _i27.ActiveDatabaseGroup);

  @override
  Duration get retryDelay =>
      (super.noSuchMethod(
            Invocation.getter(#retryDelay),
            returnValue: _FakeDuration_4(this, Invocation.getter(#retryDelay)),
          )
          as Duration);

  @override
  _i6.Future<void> get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool get connected =>
      (super.noSuchMethod(Invocation.getter(#connected), returnValue: false)
          as bool);

  @override
  set schema(_i3.Schema? schema) => super.noSuchMethod(
    Invocation.setter(#schema, schema),
    returnValueForMissingStub: null,
  );

  @override
  set clientParams(Map<String, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#clientParams, value),
    returnValueForMissingStub: null,
  );

  @override
  set updates(_i6.Stream<_i4.UpdateNotification>? value) => super.noSuchMethod(
    Invocation.setter(#updates, value),
    returnValueForMissingStub: null,
  );

  @override
  set retryDelay(Duration? value) => super.noSuchMethod(
    Invocation.setter(#retryDelay, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.ResultSet> execute(
    String? sql, [
    List<Object?>? parameters = const [],
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sql, parameters]),
            returnValue: _i6.Future<_i7.ResultSet>.value(
              _i26.dummyValue<_i7.ResultSet>(
                this,
                Invocation.method(#execute, [sql, parameters]),
              ),
            ),
          )
          as _i6.Future<_i7.ResultSet>);

  @override
  _i6.Future<_i7.ResultSet> getAll(
    String? sql, [
    List<Object?>? parameters = const [],
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [sql, parameters]),
            returnValue: _i6.Future<_i7.ResultSet>.value(
              _i26.dummyValue<_i7.ResultSet>(
                this,
                Invocation.method(#getAll, [sql, parameters]),
              ),
            ),
          )
          as _i6.Future<_i7.ResultSet>);

  @override
  _i6.Future<_i7.Row> get(
    String? sql, [
    List<Object?>? parameters = const [],
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#get, [sql, parameters]),
            returnValue: _i6.Future<_i7.Row>.value(
              _i26.dummyValue<_i7.Row>(
                this,
                Invocation.method(#get, [sql, parameters]),
              ),
            ),
          )
          as _i6.Future<_i7.Row>);

  @override
  _i6.Future<_i7.Row?> getOptional(
    String? sql, [
    List<Object?>? parameters = const [],
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getOptional, [sql, parameters]),
            returnValue: _i6.Future<_i7.Row?>.value(),
          )
          as _i6.Future<_i7.Row?>);

  @override
  _i6.Stream<_i7.ResultSet> watch(
    String? sql, {
    List<Object?>? parameters = const [],
    Duration? throttle = const Duration(milliseconds: 30),
    Iterable<String>? triggerOnTables,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #watch,
              [sql],
              {
                #parameters: parameters,
                #throttle: throttle,
                #triggerOnTables: triggerOnTables,
              },
            ),
            returnValue: _i6.Stream<_i7.ResultSet>.empty(),
          )
          as _i6.Stream<_i7.ResultSet>);

  @override
  _i6.Stream<_i4.UpdateNotification> onChange(
    Iterable<String>? tables, {
    Duration? throttle = const Duration(milliseconds: 30),
    bool? triggerImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #onChange,
              [tables],
              {#throttle: throttle, #triggerImmediately: triggerImmediately},
            ),
            returnValue: _i6.Stream<_i4.UpdateNotification>.empty(),
          )
          as _i6.Stream<_i4.UpdateNotification>);

  @override
  _i6.Future<T> readTransaction<T>(
    _i6.Future<T> Function(_i4.SqliteReadContext)? callback, {
    Duration? lockTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readTransaction,
              [callback],
              {#lockTimeout: lockTimeout},
            ),
            returnValue:
                _i26.ifNotNull(
                  _i26.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #readTransaction,
                      [callback],
                      {#lockTimeout: lockTimeout},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_5<T>(
                  this,
                  Invocation.method(
                    #readTransaction,
                    [callback],
                    {#lockTimeout: lockTimeout},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> writeTransaction<T>(
    _i6.Future<T> Function(_i4.SqliteWriteContext)? callback, {
    Duration? lockTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeTransaction,
              [callback],
              {#lockTimeout: lockTimeout},
            ),
            returnValue:
                _i26.ifNotNull(
                  _i26.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #writeTransaction,
                      [callback],
                      {#lockTimeout: lockTimeout},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_5<T>(
                  this,
                  Invocation.method(
                    #writeTransaction,
                    [callback],
                    {#lockTimeout: lockTimeout},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> computeWithDatabase<T>(
    _i6.Future<T> Function(_i7.CommonDatabase)? compute,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [compute]),
            returnValue:
                _i26.ifNotNull(
                  _i26.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#computeWithDatabase, [compute]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_5<T>(
                  this,
                  Invocation.method(#computeWithDatabase, [compute]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> executeBatch(
    String? sql,
    List<List<Object?>>? parameterSets,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#executeBatch, [sql, parameterSets]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> executeMultiple(String? sql) =>
      (super.noSuchMethod(
            Invocation.method(#executeMultiple, [sql]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refreshSchema() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSchema, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> getAutoCommit() =>
      (super.noSuchMethod(
            Invocation.method(#getAutoCommit, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<T> readLock<T>(
    _i6.Future<T> Function(_i4.SqliteReadContext)? callback, {
    String? debugContext,
    Duration? lockTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #readLock,
              [callback],
              {#debugContext: debugContext, #lockTimeout: lockTimeout},
            ),
            returnValue:
                _i26.ifNotNull(
                  _i26.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #readLock,
                      [callback],
                      {#debugContext: debugContext, #lockTimeout: lockTimeout},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_5<T>(
                  this,
                  Invocation.method(
                    #readLock,
                    [callback],
                    {#debugContext: debugContext, #lockTimeout: lockTimeout},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> writeLock<T>(
    _i6.Future<T> Function(_i4.SqliteWriteContext)? callback, {
    String? debugContext,
    Duration? lockTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeLock,
              [callback],
              {#debugContext: debugContext, #lockTimeout: lockTimeout},
            ),
            returnValue:
                _i26.ifNotNull(
                  _i26.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #writeLock,
                      [callback],
                      {#debugContext: debugContext, #lockTimeout: lockTimeout},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_5<T>(
                  this,
                  Invocation.method(
                    #writeLock,
                    [callback],
                    {#debugContext: debugContext, #lockTimeout: lockTimeout},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> baseInit() =>
      (super.noSuchMethod(
            Invocation.method(#baseInit, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> waitForFirstSync({_i8.StreamPriority? priority}) =>
      (super.noSuchMethod(
            Invocation.method(#waitForFirstSync, [], {#priority: priority}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void setStatus(_i8.SyncStatus? status) => super.noSuchMethod(
    Invocation.method(#setStatus, [status]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> connect({
    required _i28.PowerSyncBackendConnector? connector,
    _i29.SyncOptions? options,
    Duration? crudThrottleTime,
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {
              #connector: connector,
              #options: options,
              #crudThrottleTime: crudThrottleTime,
              #params: params,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> connectInternal({
    required _i28.PowerSyncBackendConnector? connector,
    required _i29.ResolvedSyncOptions? options,
    required List<({String name, String parameters})>? initiallyActiveStreams,
    required _i6.Stream<List<({String name, String parameters})>>?
    activeStreams,
    required _i30.AbortController? abort,
    required _i6.Zone? asyncWorkZone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectInternal, [], {
              #connector: connector,
              #options: options,
              #initiallyActiveStreams: initiallyActiveStreams,
              #activeStreams: activeStreams,
              #abort: abort,
              #asyncWorkZone: asyncWorkZone,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnectAndClear({bool? clearLocal = true}) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectAndClear, [], {
              #clearLocal: clearLocal,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnectedAndClear() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectedAndClear, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateSchema(_i3.Schema? schema) =>
      (super.noSuchMethod(
            Invocation.method(#updateSchema, [schema]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i4.IsolateConnectionFactory<_i7.CommonDatabase> isolateConnectionFactory() =>
      (super.noSuchMethod(
            Invocation.method(#isolateConnectionFactory, []),
            returnValue: _FakeIsolateConnectionFactory_6<_i7.CommonDatabase>(
              this,
              Invocation.method(#isolateConnectionFactory, []),
            ),
          )
          as _i4.IsolateConnectionFactory<_i7.CommonDatabase>);

  @override
  _i6.Future<String> getClientId() =>
      (super.noSuchMethod(
            Invocation.method(#getClientId, []),
            returnValue: _i6.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#getClientId, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i8.UploadQueueStats> getUploadQueueStats({
    bool? includeSize = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadQueueStats, [], {
              #includeSize: includeSize,
            }),
            returnValue: _i6.Future<_i8.UploadQueueStats>.value(
              _FakeUploadQueueStats_7(
                this,
                Invocation.method(#getUploadQueueStats, [], {
                  #includeSize: includeSize,
                }),
              ),
            ),
          )
          as _i6.Future<_i8.UploadQueueStats>);

  @override
  _i6.Future<_i31.CrudBatch?> getCrudBatch({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#getCrudBatch, [], {#limit: limit}),
            returnValue: _i6.Future<_i31.CrudBatch?>.value(),
          )
          as _i6.Future<_i31.CrudBatch?>);

  @override
  _i6.Future<_i31.CrudTransaction?> getNextCrudTransaction() =>
      (super.noSuchMethod(
            Invocation.method(#getNextCrudTransaction, []),
            returnValue: _i6.Future<_i31.CrudTransaction?>.value(),
          )
          as _i6.Future<_i31.CrudTransaction?>);

  @override
  _i6.Stream<_i31.CrudTransaction> getCrudTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getCrudTransactions, []),
            returnValue: _i6.Stream<_i31.CrudTransaction>.empty(),
          )
          as _i6.Stream<_i31.CrudTransaction>);

  @override
  _i9.SyncStream syncStream(String? name, [Map<String, Object?>? parameters]) =>
      (super.noSuchMethod(
            Invocation.method(#syncStream, [name, parameters]),
            returnValue: _FakeSyncStream_8(
              this,
              Invocation.method(#syncStream, [name, parameters]),
            ),
          )
          as _i9.SyncStream);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i10.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_9(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i10.FunctionsClient);

  @override
  _i10.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_10(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i10.SupabaseStorageClient);

  @override
  _i10.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_11(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i10.RealtimeClient);

  @override
  _i10.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_12(
              this,
              Invocation.getter(#rest),
            ),
          )
          as _i10.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i10.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_13(this, Invocation.getter(#auth)),
          )
          as _i10.GoTrueClient);

  @override
  set functions(_i10.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i10.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i10.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i10.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i10.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_14(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i10.SupabaseQueryBuilder);

  @override
  _i10.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_15(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i10.SupabaseQuerySchema);

  @override
  _i10.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_16<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i10.PostgrestFilterBuilder<T>);

  @override
  _i10.RealtimeChannel channel(
    String? name, {
    _i10.RealtimeChannelConfig? opts = const _i10.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_17(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i10.RealtimeChannel);

  @override
  List<_i10.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i10.RealtimeChannel>[],
          )
          as List<_i10.RealtimeChannel>);

  @override
  _i6.Future<String> removeChannel(_i10.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i6.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
