// Mocks generated by Mockito 5.4.6 from annotations
// in search_cms/test/features/dashboard/presentation/pages/dashboard_home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:bloc/bloc.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:search_cms/core/utils/class_templates/result.dart' as _i14;
import 'package:search_cms/features/dashboard/domain/usecases/dashboard_usecases.dart'
    as _i15;
import 'package:search_cms/features/dashboard/domain/usecases/get_all_areas_usecase.dart'
    as _i3;
import 'package:search_cms/features/dashboard/domain/usecases/get_all_levels_usecase.dart'
    as _i5;
import 'package:search_cms/features/dashboard/domain/usecases/get_all_sites_usecase.dart'
    as _i2;
import 'package:search_cms/features/dashboard/domain/usecases/get_all_table_rows_usecase.dart'
    as _i6;
import 'package:search_cms/features/dashboard/domain/usecases/get_all_units_usecase.dart'
    as _i4;
import 'package:search_cms/features/dashboard/domain/usecases/insert_area_usecase.dart'
    as _i8;
import 'package:search_cms/features/dashboard/domain/usecases/insert_artifact_usecase.dart'
    as _i13;
import 'package:search_cms/features/dashboard/domain/usecases/insert_assemblage_usecase.dart'
    as _i12;
import 'package:search_cms/features/dashboard/domain/usecases/insert_level_usecase.dart'
    as _i11;
import 'package:search_cms/features/dashboard/domain/usecases/insert_site_area_usecase.dart'
    as _i9;
import 'package:search_cms/features/dashboard/domain/usecases/insert_site_usecase.dart'
    as _i7;
import 'package:search_cms/features/dashboard/domain/usecases/insert_unit_usecase.dart'
    as _i10;
import 'package:search_cms/features/dashboard/presentation/bloc/home_cubit.dart'
    as _i17;
import 'package:search_cms/features/dashboard/presentation/bloc/home_state.dart'
    as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetAllSitesUseCase_0 extends _i1.SmartFake
    implements _i2.GetAllSitesUseCase {
  _FakeGetAllSitesUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllAreasUseCase_1 extends _i1.SmartFake
    implements _i3.GetAllAreasUseCase {
  _FakeGetAllAreasUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllUnitsUseCase_2 extends _i1.SmartFake
    implements _i4.GetAllUnitsUseCase {
  _FakeGetAllUnitsUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllLevelsUseCase_3 extends _i1.SmartFake
    implements _i5.GetAllLevelsUseCase {
  _FakeGetAllLevelsUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllTableRowsUseCase_4 extends _i1.SmartFake
    implements _i6.GetAllTableRowsUseCase {
  _FakeGetAllTableRowsUseCase_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertSiteUsecase_5 extends _i1.SmartFake
    implements _i7.InsertSiteUsecase {
  _FakeInsertSiteUsecase_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertAreaUsecase_6 extends _i1.SmartFake
    implements _i8.InsertAreaUsecase {
  _FakeInsertAreaUsecase_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertSiteAreaUsecase_7 extends _i1.SmartFake
    implements _i9.InsertSiteAreaUsecase {
  _FakeInsertSiteAreaUsecase_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertUnitUsecase_8 extends _i1.SmartFake
    implements _i10.InsertUnitUsecase {
  _FakeInsertUnitUsecase_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertLevelUsecase_9 extends _i1.SmartFake
    implements _i11.InsertLevelUsecase {
  _FakeInsertLevelUsecase_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertAssemblageUsecase_10 extends _i1.SmartFake
    implements _i12.InsertAssemblageUsecase {
  _FakeInsertAssemblageUsecase_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertArtifactUsecase_11 extends _i1.SmartFake
    implements _i13.InsertArtifactUsecase {
  _FakeInsertArtifactUsecase_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResult_12 extends _i1.SmartFake implements _i14.Result {
  _FakeResult_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardUsecases_13 extends _i1.SmartFake
    implements _i15.DashboardUsecases {
  _FakeDashboardUsecases_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DashboardUsecases].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardUsecases extends _i1.Mock implements _i15.DashboardUsecases {
  @override
  _i2.GetAllSitesUseCase get getAllSitesUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getAllSitesUseCase),
            returnValue: _FakeGetAllSitesUseCase_0(
              this,
              Invocation.getter(#getAllSitesUseCase),
            ),
            returnValueForMissingStub: _FakeGetAllSitesUseCase_0(
              this,
              Invocation.getter(#getAllSitesUseCase),
            ),
          )
          as _i2.GetAllSitesUseCase);

  @override
  _i3.GetAllAreasUseCase get getAllAreasUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getAllAreasUseCase),
            returnValue: _FakeGetAllAreasUseCase_1(
              this,
              Invocation.getter(#getAllAreasUseCase),
            ),
            returnValueForMissingStub: _FakeGetAllAreasUseCase_1(
              this,
              Invocation.getter(#getAllAreasUseCase),
            ),
          )
          as _i3.GetAllAreasUseCase);

  @override
  _i4.GetAllUnitsUseCase get getAllUnitsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getAllUnitsUseCase),
            returnValue: _FakeGetAllUnitsUseCase_2(
              this,
              Invocation.getter(#getAllUnitsUseCase),
            ),
            returnValueForMissingStub: _FakeGetAllUnitsUseCase_2(
              this,
              Invocation.getter(#getAllUnitsUseCase),
            ),
          )
          as _i4.GetAllUnitsUseCase);

  @override
  _i5.GetAllLevelsUseCase get getAllLevelsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getAllLevelsUseCase),
            returnValue: _FakeGetAllLevelsUseCase_3(
              this,
              Invocation.getter(#getAllLevelsUseCase),
            ),
            returnValueForMissingStub: _FakeGetAllLevelsUseCase_3(
              this,
              Invocation.getter(#getAllLevelsUseCase),
            ),
          )
          as _i5.GetAllLevelsUseCase);

  @override
  _i6.GetAllTableRowsUseCase get getAllTableRowsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getAllTableRowsUseCase),
            returnValue: _FakeGetAllTableRowsUseCase_4(
              this,
              Invocation.getter(#getAllTableRowsUseCase),
            ),
            returnValueForMissingStub: _FakeGetAllTableRowsUseCase_4(
              this,
              Invocation.getter(#getAllTableRowsUseCase),
            ),
          )
          as _i6.GetAllTableRowsUseCase);

  @override
  _i7.InsertSiteUsecase get insertSiteUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#insertSiteUsecase),
            returnValue: _FakeInsertSiteUsecase_5(
              this,
              Invocation.getter(#insertSiteUsecase),
            ),
            returnValueForMissingStub: _FakeInsertSiteUsecase_5(
              this,
              Invocation.getter(#insertSiteUsecase),
            ),
          )
          as _i7.InsertSiteUsecase);

  @override
  _i8.InsertAreaUsecase get insertAreaUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#insertAreaUsecase),
            returnValue: _FakeInsertAreaUsecase_6(
              this,
              Invocation.getter(#insertAreaUsecase),
            ),
            returnValueForMissingStub: _FakeInsertAreaUsecase_6(
              this,
              Invocation.getter(#insertAreaUsecase),
            ),
          )
          as _i8.InsertAreaUsecase);

  @override
  _i9.InsertSiteAreaUsecase get insertSiteAreaUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#insertSiteAreaUsecase),
            returnValue: _FakeInsertSiteAreaUsecase_7(
              this,
              Invocation.getter(#insertSiteAreaUsecase),
            ),
            returnValueForMissingStub: _FakeInsertSiteAreaUsecase_7(
              this,
              Invocation.getter(#insertSiteAreaUsecase),
            ),
          )
          as _i9.InsertSiteAreaUsecase);

  @override
  _i10.InsertUnitUsecase get insertUnitUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#insertUnitUsecase),
            returnValue: _FakeInsertUnitUsecase_8(
              this,
              Invocation.getter(#insertUnitUsecase),
            ),
            returnValueForMissingStub: _FakeInsertUnitUsecase_8(
              this,
              Invocation.getter(#insertUnitUsecase),
            ),
          )
          as _i10.InsertUnitUsecase);

  @override
  _i11.InsertLevelUsecase get insertLevelUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#insertLevelUsecase),
            returnValue: _FakeInsertLevelUsecase_9(
              this,
              Invocation.getter(#insertLevelUsecase),
            ),
            returnValueForMissingStub: _FakeInsertLevelUsecase_9(
              this,
              Invocation.getter(#insertLevelUsecase),
            ),
          )
          as _i11.InsertLevelUsecase);

  @override
  _i12.InsertAssemblageUsecase get insertAssemblageUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#insertAssemblageUsecase),
            returnValue: _FakeInsertAssemblageUsecase_10(
              this,
              Invocation.getter(#insertAssemblageUsecase),
            ),
            returnValueForMissingStub: _FakeInsertAssemblageUsecase_10(
              this,
              Invocation.getter(#insertAssemblageUsecase),
            ),
          )
          as _i12.InsertAssemblageUsecase);

  @override
  _i13.InsertArtifactUsecase get insertArtifactUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#insertArtifactUsecase),
            returnValue: _FakeInsertArtifactUsecase_11(
              this,
              Invocation.getter(#insertArtifactUsecase),
            ),
            returnValueForMissingStub: _FakeInsertArtifactUsecase_11(
              this,
              Invocation.getter(#insertArtifactUsecase),
            ),
          )
          as _i13.InsertArtifactUsecase);
}

/// A class which mocks [GetAllTableRowsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllTableRowsUseCase extends _i1.Mock
    implements _i6.GetAllTableRowsUseCase {
  @override
  _i16.Future<_i14.Result> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i16.Future<_i14.Result>.value(
              _FakeResult_12(this, Invocation.method(#call, [])),
            ),
            returnValueForMissingStub: _i16.Future<_i14.Result>.value(
              _FakeResult_12(this, Invocation.method(#call, [])),
            ),
          )
          as _i16.Future<_i14.Result>);
}

/// A class which mocks [HomeCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeCubit extends _i1.Mock implements _i17.HomeCubit {
  @override
  _i15.DashboardUsecases get dashboardUsecases =>
      (super.noSuchMethod(
            Invocation.getter(#dashboardUsecases),
            returnValue: _FakeDashboardUsecases_13(
              this,
              Invocation.getter(#dashboardUsecases),
            ),
            returnValueForMissingStub: _FakeDashboardUsecases_13(
              this,
              Invocation.getter(#dashboardUsecases),
            ),
          )
          as _i15.DashboardUsecases);

  @override
  set dashboardUsecases(_i15.DashboardUsecases? value) => super.noSuchMethod(
    Invocation.setter(#dashboardUsecases, value),
    returnValueForMissingStub: null,
  );

  @override
  _i18.HomeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i19.dummyValue<_i18.HomeState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i19.dummyValue<_i18.HomeState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i18.HomeState);

  @override
  _i16.Stream<_i18.HomeState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i18.HomeState>.empty(),
            returnValueForMissingStub: _i16.Stream<_i18.HomeState>.empty(),
          )
          as _i16.Stream<_i18.HomeState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i16.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void updateSearchToggle(int? index) => super.noSuchMethod(
    Invocation.method(#updateSearchToggle, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSelectedColumns(Set<String>? columns) => super.noSuchMethod(
    Invocation.method(#updateSelectedColumns, [columns]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i18.HomeState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i20.Change<_i18.HomeState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}
