// Mocks generated by Mockito 5.4.6 from annotations
// in search_cms/test/features/authentication/mocks/authentication_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:search_cms/core/utils/class_templates/result.dart' as _i2;
import 'package:search_cms/features/authentication/data/data_sources/abstract_authentication_sign_in_api.dart'
    as _i5;
import 'package:search_cms/features/authentication/data/models/user_model.dart'
    as _i6;
import 'package:search_cms/features/authentication/domain/repositories/abstract_authentication_sign_in_repository.dart'
    as _i7;
import 'package:supabase/supabase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0 extends _i1.SmartFake implements _i2.Result {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_1 extends _i1.SmartFake
    implements _i3.FunctionsClient {
  _FakeFunctionsClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_2 extends _i1.SmartFake
    implements _i3.SupabaseStorageClient {
  _FakeSupabaseStorageClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_3 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_4 extends _i1.SmartFake
    implements _i3.PostgrestClient {
  _FakePostgrestClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_5 extends _i1.SmartFake implements _i3.GoTrueClient {
  _FakeGoTrueClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_6 extends _i1.SmartFake
    implements _i3.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_7 extends _i1.SmartFake
    implements _i3.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_8<T1> extends _i1.SmartFake
    implements _i3.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_9 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueAdminApi_10 extends _i1.SmartFake
    implements _i3.GoTrueAdminApi {
  _FakeGoTrueAdminApi_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueMFAApi_11 extends _i1.SmartFake implements _i3.GoTrueMFAApi {
  _FakeGoTrueMFAApi_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_12 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthResponse_13 extends _i1.SmartFake implements _i3.OAuthResponse {
  _FakeOAuthResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSessionUrlResponse_14 extends _i1.SmartFake
    implements _i3.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResendResponse_15 extends _i1.SmartFake
    implements _i3.ResendResponse {
  _FakeResendResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_16 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObject_17 extends _i1.SmartFake implements Object {
  _FakeObject_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_18 extends _i1.SmartFake implements _i3.User {
  _FakeUser_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_19 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStreamFilterBuilder_20 extends _i1.SmartFake
    implements _i3.SupabaseStreamFilterBuilder {
  _FakeSupabaseStreamFilterBuilder_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePostgrestQueryBuilder_21<T> extends _i1.SmartFake
    implements _i3.PostgrestQueryBuilder<T> {
  _FakePostgrestQueryBuilder_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestBuilder_22<T, S, R> extends _i1.SmartFake
    implements _i3.PostgrestBuilder<T, S, R> {
  _FakePostgrestBuilder_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_23 extends _i1.SmartFake implements Uri {
  _FakeUri_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_24<T> extends _i1.SmartFake implements _i4.Future<T> {
  _FakeFuture_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestTransformBuilder_25<T> extends _i1.SmartFake
    implements _i3.PostgrestTransformBuilder<T> {
  _FakePostgrestTransformBuilder_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponsePostgrestBuilder_26<T, S, R> extends _i1.SmartFake
    implements _i3.ResponsePostgrestBuilder<T, S, R> {
  _FakeResponsePostgrestBuilder_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AbstractAuthenticationSignInApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractAuthenticationSignInApi extends _i1.Mock
    implements _i5.AbstractAuthenticationSignInApi {
  @override
  _i4.Future<_i6.UserModel?> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<_i6.UserModel?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.UserModel?>.value(),
          )
          as _i4.Future<_i6.UserModel?>);
}

/// A class which mocks [AbstractAuthenticationSignInRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractAuthenticationSignInRepository extends _i1.Mock
    implements _i7.AbstractAuthenticationSignInRepository {
  @override
  _i4.Future<_i2.Result> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<_i2.Result>.value(
              _FakeResult_0(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Result>.value(
              _FakeResult_0(
                this,
                Invocation.method(#signIn, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.Result>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i3.SupabaseClient {
  @override
  _i3.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_1(
              this,
              Invocation.getter(#functions),
            ),
            returnValueForMissingStub: _FakeFunctionsClient_1(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i3.FunctionsClient);

  @override
  _i3.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_2(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeSupabaseStorageClient_2(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.SupabaseStorageClient);

  @override
  _i3.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_3(
              this,
              Invocation.getter(#realtime),
            ),
            returnValueForMissingStub: _FakeRealtimeClient_3(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i3.RealtimeClient);

  @override
  _i3.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_4(this, Invocation.getter(#rest)),
            returnValueForMissingStub: _FakePostgrestClient_4(
              this,
              Invocation.getter(#rest),
            ),
          )
          as _i3.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i3.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_5(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeGoTrueClient_5(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i3.GoTrueClient);

  @override
  set functions(_i3.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i3.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i3.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i3.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i3.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_6(
              this,
              Invocation.method(#from, [table]),
            ),
            returnValueForMissingStub: _FakeSupabaseQueryBuilder_6(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i3.SupabaseQueryBuilder);

  @override
  _i3.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_7(
              this,
              Invocation.method(#schema, [schema]),
            ),
            returnValueForMissingStub: _FakeSupabaseQuerySchema_7(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i3.SupabaseQuerySchema);

  @override
  _i3.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_8<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i3.PostgrestFilterBuilder<T>);

  @override
  _i3.RealtimeChannel channel(
    String? name, {
    _i3.RealtimeChannelConfig? opts = const _i3.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_9(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_9(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  List<_i3.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i3.RealtimeChannel>[],
            returnValueForMissingStub: <_i3.RealtimeChannel>[],
          )
          as List<_i3.RealtimeChannel>);

  @override
  _i4.Future<String> removeChannel(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i4.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i3.GoTrueClient {
  @override
  _i3.GoTrueAdminApi get admin =>
      (super.noSuchMethod(
            Invocation.getter(#admin),
            returnValue: _FakeGoTrueAdminApi_10(
              this,
              Invocation.getter(#admin),
            ),
            returnValueForMissingStub: _FakeGoTrueAdminApi_10(
              this,
              Invocation.getter(#admin),
            ),
          )
          as _i3.GoTrueAdminApi);

  @override
  _i3.GoTrueMFAApi get mfa =>
      (super.noSuchMethod(
            Invocation.getter(#mfa),
            returnValue: _FakeGoTrueMFAApi_11(this, Invocation.getter(#mfa)),
            returnValueForMissingStub: _FakeGoTrueMFAApi_11(
              this,
              Invocation.getter(#mfa),
            ),
          )
          as _i3.GoTrueMFAApi);

  @override
  _i4.Stream<_i3.AuthState> get onAuthStateChange =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChange),
            returnValue: _i4.Stream<_i3.AuthState>.empty(),
            returnValueForMissingStub: _i4.Stream<_i3.AuthState>.empty(),
          )
          as _i4.Stream<_i3.AuthState>);

  @override
  _i4.Stream<_i3.AuthState> get onAuthStateChangeSync =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChangeSync),
            returnValue: _i4.Stream<_i3.AuthState>.empty(),
            returnValueForMissingStub: _i4.Stream<_i3.AuthState>.empty(),
          )
          as _i4.Stream<_i3.AuthState>);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  set admin(_i3.GoTrueAdminApi? value) => super.noSuchMethod(
    Invocation.setter(#admin, value),
    returnValueForMissingStub: null,
  );

  @override
  set mfa(_i3.GoTrueMFAApi? value) => super.noSuchMethod(
    Invocation.setter(#mfa, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i3.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, [], {
              #data: data,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i3.OtpChannel? channel = _i3.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.OAuthResponse> getOAuthSignInUrl({
    required _i3.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOAuthSignInUrl, [], {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            }),
            returnValue: _i4.Future<_i3.OAuthResponse>.value(
              _FakeOAuthResponse_13(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.OAuthResponse>.value(
              _FakeOAuthResponse_13(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.OAuthResponse>);

  @override
  _i4.Future<_i3.AuthSessionUrlResponse> exchangeCodeForSession(
    String? authCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForSession, [authCode]),
            returnValue: _i4.Future<_i3.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_14(
                this,
                Invocation.method(#exchangeCodeForSession, [authCode]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.AuthSessionUrlResponse>.value(
                  _FakeAuthSessionUrlResponse_14(
                    this,
                    Invocation.method(#exchangeCodeForSession, [authCode]),
                  ),
                ),
          )
          as _i4.Future<_i3.AuthSessionUrlResponse>);

  @override
  _i4.Future<_i3.AuthResponse> signInWithIdToken({
    required _i3.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i3.OtpChannel? channel = _i3.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOtp, [], {
              #email: email,
              #phone: phone,
              #emailRedirectTo: emailRedirectTo,
              #shouldCreateUser: shouldCreateUser,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i3.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSSOSignInUrl, [], {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i3.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, [refreshToken]),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<void> reauthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.ResendResponse> resend({
    String? email,
    String? phone,
    required _i3.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resend, [], {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.ResendResponse>.value(
              _FakeResendResponse_15(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.ResendResponse>.value(
              _FakeResendResponse_15(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.ResendResponse>);

  @override
  _i4.Future<_i3.UserResponse> getUser([String? jwt]) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [jwt]),
            returnValue: _i4.Future<_i3.UserResponse>.value(
              _FakeUserResponse_16(this, Invocation.method(#getUser, [jwt])),
            ),
            returnValueForMissingStub: _i4.Future<_i3.UserResponse>.value(
              _FakeUserResponse_16(this, Invocation.method(#getUser, [jwt])),
            ),
          )
          as _i4.Future<_i3.UserResponse>);

  @override
  _i4.Future<_i3.UserResponse> updateUser(
    _i3.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [attributes],
              {#emailRedirectTo: emailRedirectTo},
            ),
            returnValue: _i4.Future<_i3.UserResponse>.value(
              _FakeUserResponse_16(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.UserResponse>.value(
              _FakeUserResponse_16(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.UserResponse>);

  @override
  _i4.Future<_i3.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [refreshToken]),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#setSession, [refreshToken]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#setSession, [refreshToken]),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSessionFromUrl,
              [originUrl],
              {#storeSession: storeSession},
            ),
            returnValue: _i4.Future<_i3.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_14(
                this,
                Invocation.method(
                  #getSessionFromUrl,
                  [originUrl],
                  {#storeSession: storeSession},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.AuthSessionUrlResponse>.value(
                  _FakeAuthSessionUrlResponse_14(
                    this,
                    Invocation.method(
                      #getSessionFromUrl,
                      [originUrl],
                      {#storeSession: storeSession},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i3.AuthSessionUrlResponse>);

  @override
  _i4.Future<void> signOut({
    _i3.SignOutScope? scope = _i3.SignOutScope.local,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#scope: scope}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetPasswordForEmail,
              [email],
              {#redirectTo: redirectTo, #captchaToken: captchaToken},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.UserIdentity>> getUserIdentities() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentities, []),
            returnValue: _i4.Future<List<_i3.UserIdentity>>.value(
              <_i3.UserIdentity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i3.UserIdentity>>.value(
              <_i3.UserIdentity>[],
            ),
          )
          as _i4.Future<List<_i3.UserIdentity>>);

  @override
  _i4.Future<_i3.AuthResponse> linkIdentityWithIdToken({
    required _i3.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkIdentityWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.OAuthResponse> getLinkIdentityUrl(
    _i3.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLinkIdentityUrl,
              [provider],
              {
                #redirectTo: redirectTo,
                #scopes: scopes,
                #queryParams: queryParams,
              },
            ),
            returnValue: _i4.Future<_i3.OAuthResponse>.value(
              _FakeOAuthResponse_13(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.OAuthResponse>.value(
              _FakeOAuthResponse_13(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i3.OAuthResponse>);

  @override
  _i4.Future<void> unlinkIdentity(_i3.UserIdentity? identity) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkIdentity, [identity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setInitialSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#setInitialSession, [jsonStr]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#recoverSession, [jsonStr]),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
    Invocation.method(#startAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
    Invocation.method(#stopAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyAllSubscribers(
    _i3.AuthChangeEvent? event, {
    _i3.Session? session,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #notifyAllSubscribers,
      [event],
      {#session: session, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Object notifyException(Object? exception, [StackTrace? stackTrace]) =>
      (super.noSuchMethod(
            Invocation.method(#notifyException, [exception, stackTrace]),
            returnValue: _FakeObject_17(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
            returnValueForMissingStub: _FakeObject_17(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
          )
          as Object);
}

/// A class which mocks [AuthResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthResponse extends _i1.Mock implements _i3.AuthResponse {}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i3.Session {
  @override
  String get accessToken =>
      (super.noSuchMethod(
            Invocation.getter(#accessToken),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
          )
          as String);

  @override
  String get tokenType =>
      (super.noSuchMethod(
            Invocation.getter(#tokenType),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#tokenType),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#tokenType),
            ),
          )
          as String);

  @override
  _i3.User get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeUser_18(this, Invocation.getter(#user)),
            returnValueForMissingStub: _FakeUser_18(
              this,
              Invocation.getter(#user),
            ),
          )
          as _i3.User);

  @override
  bool get isExpired =>
      (super.noSuchMethod(
            Invocation.getter(#isExpired),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set expiresAt(int? value) => super.noSuchMethod(
    Invocation.setter(#expiresAt, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Session copyWith({
    String? accessToken,
    int? expiresIn,
    String? refreshToken,
    String? tokenType,
    String? providerToken,
    String? providerRefreshToken,
    _i3.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #accessToken: accessToken,
              #expiresIn: expiresIn,
              #refreshToken: refreshToken,
              #tokenType: tokenType,
              #providerToken: providerToken,
              #providerRefreshToken: providerRefreshToken,
              #user: user,
            }),
            returnValue: _FakeSession_19(
              this,
              Invocation.method(#copyWith, [], {
                #accessToken: accessToken,
                #expiresIn: expiresIn,
                #refreshToken: refreshToken,
                #tokenType: tokenType,
                #providerToken: providerToken,
                #providerRefreshToken: providerRefreshToken,
                #user: user,
              }),
            ),
            returnValueForMissingStub: _FakeSession_19(
              this,
              Invocation.method(#copyWith, [], {
                #accessToken: accessToken,
                #expiresIn: expiresIn,
                #refreshToken: refreshToken,
                #tokenType: tokenType,
                #providerToken: providerToken,
                #providerRefreshToken: providerRefreshToken,
                #user: user,
              }),
            ),
          )
          as _i3.Session);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#aud)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#aud),
            ),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [SupabaseQueryBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseQueryBuilder extends _i1.Mock
    implements _i3.SupabaseQueryBuilder {
  @override
  _i3.SupabaseStreamFilterBuilder stream({required List<String>? primaryKey}) =>
      (super.noSuchMethod(
            Invocation.method(#stream, [], {#primaryKey: primaryKey}),
            returnValue: _FakeSupabaseStreamFilterBuilder_20(
              this,
              Invocation.method(#stream, [], {#primaryKey: primaryKey}),
            ),
            returnValueForMissingStub: _FakeSupabaseStreamFilterBuilder_20(
              this,
              Invocation.method(#stream, [], {#primaryKey: primaryKey}),
            ),
          )
          as _i3.SupabaseStreamFilterBuilder);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<dynamic> insert(
    Object? values, {
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insert,
              [values],
              {#defaultToNull: defaultToNull},
            ),
            returnValue: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(
                #insert,
                [values],
                {#defaultToNull: defaultToNull},
              ),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(
                #insert,
                [values],
                {#defaultToNull: defaultToNull},
              ),
            ),
          )
          as _i3.PostgrestFilterBuilder<dynamic>);

  @override
  _i3.PostgrestFilterBuilder<dynamic> upsert(
    Object? values, {
    String? onConflict,
    bool? ignoreDuplicates = false,
    bool? defaultToNull = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsert,
              [values],
              {
                #onConflict: onConflict,
                #ignoreDuplicates: ignoreDuplicates,
                #defaultToNull: defaultToNull,
              },
            ),
            returnValue: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(
                #upsert,
                [values],
                {
                  #onConflict: onConflict,
                  #ignoreDuplicates: ignoreDuplicates,
                  #defaultToNull: defaultToNull,
                },
              ),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(
                #upsert,
                [values],
                {
                  #onConflict: onConflict,
                  #ignoreDuplicates: ignoreDuplicates,
                  #defaultToNull: defaultToNull,
                },
              ),
            ),
          )
          as _i3.PostgrestFilterBuilder<dynamic>);

  @override
  _i3.PostgrestFilterBuilder<dynamic> update(Map<dynamic, dynamic>? values) =>
      (super.noSuchMethod(
            Invocation.method(#update, [values]),
            returnValue: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#update, [values]),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#update, [values]),
            ),
          )
          as _i3.PostgrestFilterBuilder<dynamic>);

  @override
  _i3.PostgrestFilterBuilder<dynamic> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#delete, []),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#delete, []),
            ),
          )
          as _i3.PostgrestFilterBuilder<dynamic>);

  @override
  _i3.PostgrestFilterBuilder<int> count([
    _i3.CountOption? option = _i3.CountOption.exact,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [option]),
            returnValue: _FakePostgrestFilterBuilder_8<int>(
              this,
              Invocation.method(#count, [option]),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<int>(
              this,
              Invocation.method(#count, [option]),
            ),
          )
          as _i3.PostgrestFilterBuilder<int>);

  @override
  _i3.PostgrestQueryBuilder<dynamic> setHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue: _FakePostgrestQueryBuilder_21<dynamic>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
            returnValueForMissingStub: _FakePostgrestQueryBuilder_21<dynamic>(
              this,
              Invocation.method(#setHeader, [key, value]),
            ),
          )
          as _i3.PostgrestQueryBuilder<dynamic>);

  @override
  _i3.PostgrestBuilder<U, U, dynamic> withConverter<U>(
    _i3.PostgrestConverter<U, dynamic>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue: _FakePostgrestBuilder_22<U, U, dynamic>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
            returnValueForMissingStub: _FakePostgrestBuilder_22<U, U, dynamic>(
              this,
              Invocation.method(#withConverter, [converter]),
            ),
          )
          as _i3.PostgrestBuilder<U, U, dynamic>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_23(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
            returnValueForMissingStub: _FakeUri_23(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value]),
            returnValue: _FakeUri_23(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
            returnValueForMissingStub: _FakeUri_23(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
          )
          as Uri);

  @override
  _i4.Stream<dynamic> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i4.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i4.Stream<dynamic>.empty(),
          )
          as _i4.Stream<dynamic>);

  @override
  _i4.Future<dynamic> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i4.Future<dynamic>.value(),
            returnValueForMissingStub: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<U> then<U>(
    _i4.FutureOr<U> Function(dynamic)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i4.Future<U>.value(v),
                ) ??
                _FakeFuture_24<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i4.Future<U>.value(v),
                ) ??
                _FakeFuture_24<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i4.Future<U>);

  @override
  _i4.Future<dynamic> timeout(
    Duration? timeLimit, {
    _i4.FutureOr<dynamic> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i4.Future<dynamic>.value(),
            returnValueForMissingStub: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> whenComplete(_i4.FutureOr<void> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i4.Future<dynamic>.value(),
            returnValueForMissingStub: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}

/// A class which mocks [PostgrestFilterBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostgrestFilterBuilder extends _i1.Mock
    implements _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> {
  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> copyWithUrl(
    Uri? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyWithUrl, [url]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#copyWithUrl, [url]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#copyWithUrl, [url]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> not(
    String? column,
    String? operator,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#not, [column, operator, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#not, [column, operator, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#not, [column, operator, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> or(
    String? filters, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #or,
              [filters],
              {#referencedTable: referencedTable},
            ),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #or,
                    [filters],
                    {#referencedTable: referencedTable},
                  ),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #or,
                    [filters],
                    {#referencedTable: referencedTable},
                  ),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> eq(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#eq, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#eq, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#eq, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> neq(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#neq, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#neq, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#neq, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> gt(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#gt, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#gt, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#gt, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> gte(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#gte, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#gte, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#gte, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> lt(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lt, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#lt, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#lt, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> lte(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#lte, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#lte, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#lte, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> like(
    String? column,
    String? pattern,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#like, [column, pattern]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#like, [column, pattern]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#like, [column, pattern]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<dynamic> likeAllOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likeAllOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#likeAllOf, [column, patterns]),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#likeAllOf, [column, patterns]),
            ),
          )
          as _i3.PostgrestFilterBuilder<dynamic>);

  @override
  _i3.PostgrestFilterBuilder<dynamic> likeAnyOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likeAnyOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#likeAnyOf, [column, patterns]),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#likeAnyOf, [column, patterns]),
            ),
          )
          as _i3.PostgrestFilterBuilder<dynamic>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> ilike(
    String? column,
    String? pattern,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ilike, [column, pattern]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#ilike, [column, pattern]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#ilike, [column, pattern]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<dynamic> ilikeAllOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ilikeAllOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#ilikeAllOf, [column, patterns]),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#ilikeAllOf, [column, patterns]),
            ),
          )
          as _i3.PostgrestFilterBuilder<dynamic>);

  @override
  _i3.PostgrestFilterBuilder<dynamic> ilikeAnyOf(
    String? column,
    List<String>? patterns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#ilikeAnyOf, [column, patterns]),
            returnValue: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#ilikeAnyOf, [column, patterns]),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_8<dynamic>(
              this,
              Invocation.method(#ilikeAnyOf, [column, patterns]),
            ),
          )
          as _i3.PostgrestFilterBuilder<dynamic>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> isFilter(
    String? column,
    bool? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isFilter, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#isFilter, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#isFilter, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> inFilter(
    String? column,
    List<dynamic>? values,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inFilter, [column, values]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#inFilter, [column, values]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#inFilter, [column, values]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> contains(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#contains, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#contains, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> containedBy(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#containedBy, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#containedBy, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#containedBy, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> rangeLt(
    String? column,
    String? range,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rangeLt, [column, range]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeLt, [column, range]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeLt, [column, range]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> rangeGt(
    String? column,
    String? range,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rangeGt, [column, range]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeGt, [column, range]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeGt, [column, range]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> rangeGte(
    String? column,
    String? range,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rangeGte, [column, range]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeGte, [column, range]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeGte, [column, range]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> rangeLte(
    String? column,
    String? range,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rangeLte, [column, range]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeLte, [column, range]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeLte, [column, range]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> rangeAdjacent(
    String? column,
    String? range,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rangeAdjacent, [column, range]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeAdjacent, [column, range]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#rangeAdjacent, [column, range]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> overlaps(
    String? column,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#overlaps, [column, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#overlaps, [column, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#overlaps, [column, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> textSearch(
    String? column,
    String? query, {
    String? config,
    _i3.TextSearchType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #textSearch,
              [column, query],
              {#config: config, #type: type},
            ),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #textSearch,
                    [column, query],
                    {#config: config, #type: type},
                  ),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #textSearch,
                    [column, query],
                    {#config: config, #type: type},
                  ),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> filter(
    String? column,
    String? operator,
    Object? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filter, [column, operator, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#filter, [column, operator, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#filter, [column, operator, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> match(
    Map<String, Object>? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#match, [query]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#match, [query]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#match, [query]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>> setHeader(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setHeader, [key, value]),
            returnValue:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#setHeader, [key, value]),
                ),
            returnValueForMissingStub:
                _FakePostgrestFilterBuilder_8<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#setHeader, [key, value]),
                ),
          )
          as _i3.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestTransformBuilder<List<Map<String, dynamic>>> select([
    String? columns = '*',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#select, [columns]),
            returnValue:
                _FakePostgrestTransformBuilder_25<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
            returnValueForMissingStub:
                _FakePostgrestTransformBuilder_25<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#select, [columns]),
                ),
          )
          as _i3.PostgrestTransformBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestTransformBuilder<List<Map<String, dynamic>>> order(
    String? column, {
    bool? ascending = false,
    bool? nullsFirst = false,
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #order,
              [column],
              {
                #ascending: ascending,
                #nullsFirst: nullsFirst,
                #referencedTable: referencedTable,
              },
            ),
            returnValue:
                _FakePostgrestTransformBuilder_25<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #order,
                    [column],
                    {
                      #ascending: ascending,
                      #nullsFirst: nullsFirst,
                      #referencedTable: referencedTable,
                    },
                  ),
                ),
            returnValueForMissingStub:
                _FakePostgrestTransformBuilder_25<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #order,
                    [column],
                    {
                      #ascending: ascending,
                      #nullsFirst: nullsFirst,
                      #referencedTable: referencedTable,
                    },
                  ),
                ),
          )
          as _i3.PostgrestTransformBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestTransformBuilder<List<Map<String, dynamic>>> limit(
    int? count, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #limit,
              [count],
              {#referencedTable: referencedTable},
            ),
            returnValue:
                _FakePostgrestTransformBuilder_25<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #limit,
                    [count],
                    {#referencedTable: referencedTable},
                  ),
                ),
            returnValueForMissingStub:
                _FakePostgrestTransformBuilder_25<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #limit,
                    [count],
                    {#referencedTable: referencedTable},
                  ),
                ),
          )
          as _i3.PostgrestTransformBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestTransformBuilder<List<Map<String, dynamic>>> range(
    int? from,
    int? to, {
    String? referencedTable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #range,
              [from, to],
              {#referencedTable: referencedTable},
            ),
            returnValue:
                _FakePostgrestTransformBuilder_25<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #range,
                    [from, to],
                    {#referencedTable: referencedTable},
                  ),
                ),
            returnValueForMissingStub:
                _FakePostgrestTransformBuilder_25<List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(
                    #range,
                    [from, to],
                    {#referencedTable: referencedTable},
                  ),
                ),
          )
          as _i3.PostgrestTransformBuilder<List<Map<String, dynamic>>>);

  @override
  _i3.PostgrestTransformBuilder<Map<String, dynamic>> single() =>
      (super.noSuchMethod(
            Invocation.method(#single, []),
            returnValue:
                _FakePostgrestTransformBuilder_25<Map<String, dynamic>>(
                  this,
                  Invocation.method(#single, []),
                ),
            returnValueForMissingStub:
                _FakePostgrestTransformBuilder_25<Map<String, dynamic>>(
                  this,
                  Invocation.method(#single, []),
                ),
          )
          as _i3.PostgrestTransformBuilder<Map<String, dynamic>>);

  @override
  _i3.PostgrestTransformBuilder<Map<String, dynamic>?> maybeSingle() =>
      (super.noSuchMethod(
            Invocation.method(#maybeSingle, []),
            returnValue:
                _FakePostgrestTransformBuilder_25<Map<String, dynamic>?>(
                  this,
                  Invocation.method(#maybeSingle, []),
                ),
            returnValueForMissingStub:
                _FakePostgrestTransformBuilder_25<Map<String, dynamic>?>(
                  this,
                  Invocation.method(#maybeSingle, []),
                ),
          )
          as _i3.PostgrestTransformBuilder<Map<String, dynamic>?>);

  @override
  _i3.PostgrestTransformBuilder<String> csv() =>
      (super.noSuchMethod(
            Invocation.method(#csv, []),
            returnValue: _FakePostgrestTransformBuilder_25<String>(
              this,
              Invocation.method(#csv, []),
            ),
            returnValueForMissingStub:
                _FakePostgrestTransformBuilder_25<String>(
                  this,
                  Invocation.method(#csv, []),
                ),
          )
          as _i3.PostgrestTransformBuilder<String>);

  @override
  _i3.ResponsePostgrestBuilder<
    _i3.PostgrestResponse<List<Map<String, dynamic>>>,
    List<Map<String, dynamic>>,
    List<Map<String, dynamic>>
  >
  count([_i3.CountOption? count = _i3.CountOption.exact]) =>
      (super.noSuchMethod(
            Invocation.method(#count, [count]),
            returnValue:
                _FakeResponsePostgrestBuilder_26<
                  _i3.PostgrestResponse<List<Map<String, dynamic>>>,
                  List<Map<String, dynamic>>,
                  List<Map<String, dynamic>>
                >(this, Invocation.method(#count, [count])),
            returnValueForMissingStub:
                _FakeResponsePostgrestBuilder_26<
                  _i3.PostgrestResponse<List<Map<String, dynamic>>>,
                  List<Map<String, dynamic>>,
                  List<Map<String, dynamic>>
                >(this, Invocation.method(#count, [count])),
          )
          as _i3.ResponsePostgrestBuilder<
            _i3.PostgrestResponse<List<Map<String, dynamic>>>,
            List<Map<String, dynamic>>,
            List<Map<String, dynamic>>
          >);

  @override
  _i3.PostgrestBuilder<void, void, void> head() =>
      (super.noSuchMethod(
            Invocation.method(#head, []),
            returnValue: _FakePostgrestBuilder_22<void, void, void>(
              this,
              Invocation.method(#head, []),
            ),
            returnValueForMissingStub:
                _FakePostgrestBuilder_22<void, void, void>(
                  this,
                  Invocation.method(#head, []),
                ),
          )
          as _i3.PostgrestBuilder<void, void, void>);

  @override
  _i3.ResponsePostgrestBuilder<
    Map<String, dynamic>,
    Map<String, dynamic>,
    Map<String, dynamic>
  >
  geojson() =>
      (super.noSuchMethod(
            Invocation.method(#geojson, []),
            returnValue:
                _FakeResponsePostgrestBuilder_26<
                  Map<String, dynamic>,
                  Map<String, dynamic>,
                  Map<String, dynamic>
                >(this, Invocation.method(#geojson, [])),
            returnValueForMissingStub:
                _FakeResponsePostgrestBuilder_26<
                  Map<String, dynamic>,
                  Map<String, dynamic>,
                  Map<String, dynamic>
                >(this, Invocation.method(#geojson, [])),
          )
          as _i3.ResponsePostgrestBuilder<
            Map<String, dynamic>,
            Map<String, dynamic>,
            Map<String, dynamic>
          >);

  @override
  _i3.PostgrestBuilder<String, String, String> explain({
    bool? analyze = false,
    bool? verbose = false,
    bool? settings = false,
    bool? buffers = false,
    bool? wal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#explain, [], {
              #analyze: analyze,
              #verbose: verbose,
              #settings: settings,
              #buffers: buffers,
              #wal: wal,
            }),
            returnValue: _FakePostgrestBuilder_22<String, String, String>(
              this,
              Invocation.method(#explain, [], {
                #analyze: analyze,
                #verbose: verbose,
                #settings: settings,
                #buffers: buffers,
                #wal: wal,
              }),
            ),
            returnValueForMissingStub:
                _FakePostgrestBuilder_22<String, String, String>(
                  this,
                  Invocation.method(#explain, [], {
                    #analyze: analyze,
                    #verbose: verbose,
                    #settings: settings,
                    #buffers: buffers,
                    #wal: wal,
                  }),
                ),
          )
          as _i3.PostgrestBuilder<String, String, String>);

  @override
  _i3.PostgrestBuilder<U, U, List<Map<String, dynamic>>> withConverter<U>(
    _i3.PostgrestConverter<U, List<Map<String, dynamic>>>? converter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [converter]),
            returnValue:
                _FakePostgrestBuilder_22<U, U, List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#withConverter, [converter]),
                ),
            returnValueForMissingStub:
                _FakePostgrestBuilder_22<U, U, List<Map<String, dynamic>>>(
                  this,
                  Invocation.method(#withConverter, [converter]),
                ),
          )
          as _i3.PostgrestBuilder<U, U, List<Map<String, dynamic>>>);

  @override
  Uri appendSearchParams(String? key, String? value, [Uri? url]) =>
      (super.noSuchMethod(
            Invocation.method(#appendSearchParams, [key, value, url]),
            returnValue: _FakeUri_23(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
            returnValueForMissingStub: _FakeUri_23(
              this,
              Invocation.method(#appendSearchParams, [key, value, url]),
            ),
          )
          as Uri);

  @override
  Uri overrideSearchParams(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#overrideSearchParams, [key, value]),
            returnValue: _FakeUri_23(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
            returnValueForMissingStub: _FakeUri_23(
              this,
              Invocation.method(#overrideSearchParams, [key, value]),
            ),
          )
          as Uri);

  @override
  _i4.Stream<List<Map<String, dynamic>>> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i4.Stream<List<Map<String, dynamic>>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i4.Stream<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<U> then<U>(
    _i4.FutureOr<U> Function(List<Map<String, dynamic>>)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i4.Future<U>.value(v),
                ) ??
                _FakeFuture_24<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<U>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (U v) => _i4.Future<U>.value(v),
                ) ??
                _FakeFuture_24<U>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i4.Future<U>);

  @override
  _i4.Future<List<Map<String, dynamic>>> timeout(
    Duration? timeLimit, {
    _i4.FutureOr<List<Map<String, dynamic>>> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> whenComplete(
    _i4.FutureOr<void> Function()? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}
