name: Flutter test

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: string

permissions:
    checks: write
    pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 

      # Set flutter working-directory
      - name: Set flutter workdir
        run: flutter config --build-dir=./
        working-directory: ./frontend/search_cms

      # Verify testing is added
      - name: Flutter source add
        run: flutter pub add dev:test
        working-directory: ./frontend/search_cms
        
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./frontend/search_cms
      
      - name: Set Timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      
      # Junit report convert flutter's json test report to jUnit
      - name: Flutter add junitreport
        run: flutter pub global activate junitreport
        working-directory: ./frontend/search_cms


      - name: Run tests 
        run: | 
          mkdir -p test-results
          flutter test --machine | tojunit --output test-results/flutter_report_${{ env.TIMESTAMP }}.xml
        working-directory: ./frontend/search_cms

      # Upload out flutter test to the artifacts
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: flutter_report_${{ env.TIMESTAMP }}
          path: frontend/search_cms/test-results/flutter_report_${{ env.TIMESTAMP }}.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'frontend/search_cms/test-results/flutter_report_${{ env.TIMESTAMP }}.xml'
          include_passed: True
          fail_on_failure: True
      
          
      