name: 'Nightly Merge'

on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  nightly-merge:

    runs-on: ubuntu-latest # Just use githubs runner for this, no need for self hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full clone necessary for proper merge

    # Add versioning
    - name: Set Version String
      id: version
      run: echo "DATE_VER=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
    # Uses a marketplace gh action that merges the develop to main, no need for testing yet.
    # This action creates a PR instead of doing a direct push
    - name: Create Pull Request to Main
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: nightly-merge-v${{ env.DATE_VER }}
        base: main
        title: 'Nightly Merge: v${{ env.DATE_VER }}'
        body: 'Automated nightly merge for version ${{ env.DATE_VER }}. This PR will auto-merge once all status checks pass.'
        commit-message: 'Automated nightly merge v${{ env.DATE_VER }}''
        delete-branch: false
  