name: 'Nightly Merge'

on:
  schedule:
    - cron:  '0 6 * * *'

jobs:

  nightly-merge:

    runs-on: ubuntu-latest # Just use githubs runner for this, no need for self hosted
    env:
      RUN_TYPE: ${{ inputs.run_type || 'default' }}
      ARTIFACT_SUFFIX: ${{ inputs.artifact_suffix || 'pr' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full clone necessary for proper merge
    - name: Install github cli
      run: sudo apt install -y gh

    - name: Authenticate github
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
    # Add versioning
    - name: Set Version String
      id: version
      run: echo "DATE_VER=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

    - name: Create branch name
      id: vars
      run: echo "BRANCH=nightly-merge-v${{ steps.version.outputs.DATE_VER }}" >> $GITHUB_OUTPUT

    # reset develop off of main to highlight commit changes between them
    - name: Prepare changes for PR
      run: |
        git checkout develop
        git pull origin develop
        git checkout -b "${{ steps.vars.outputs.BRANCH }}"
        git push origin "${{ steps.vars.outputs.BRANCH }}"
    # Uses a marketplace gh action that merges the develop to main
    # This action creates a PR instead of doing a direct push
    - name: Create Pull Request to Main
      run: |
        gh pr create \
          --title "Nightly Merge: ${{ steps.version.outputs.DATE_VER }}" \
          --body "Automated nightly merge for version ${{ steps.version.outputs.DATE_VER }}. This PR will auto-merge once all status checks pass." \
          --base main \
          --head "${{ steps.vars.outputs.BRANCH }}"  
